# Generated by Django 5.2.8 on 2025-11-15 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название НКО')),
                ('description', models.TextField(verbose_name='Описание деятельности')),
                ('mission', models.TextField(blank=True, verbose_name='Миссия организации')),
                ('category', models.CharField(choices=[('ecology', 'Экология'), ('animals', 'Защита животных'), ('children', 'Помощь детям'), ('elderly', 'Помощь пожилым'), ('sport', 'Спорт'), ('culture', 'Культура'), ('education', 'Образование'), ('health', 'Здравоохранение')], max_length=20, verbose_name='Категория')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Соцсети')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('logo', models.ImageField(blank=True, upload_to='nko/logos/', verbose_name='Логотип')),
                ('cover_image', models.ImageField(blank=True, upload_to='nko/covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_nkos', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='NKOMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('volunteer', 'Волонтер'), ('coordinator', 'Координатор'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=20, verbose_name='Роль')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен'), ('banned', 'Заблокирован')], default='pending', max_length=20, verbose_name='Статус')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('skills', models.CharField(blank=True, max_length=500, verbose_name='Навыки')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Вступил')),
                ('nko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.nko', verbose_name='НКО')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Членство в НКО',
                'verbose_name_plural': 'Членства в НКО',
                'unique_together': {('user', 'nko')},
            },
        ),
    ]
