# Generated by Django 5.2.8 on 2025-11-15 11:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('role', models.CharField(choices=[('volunteer', 'Волонтер'), ('nko_representative', 'Представитель НКО'), ('corporate_volunteer', 'Корпоративный волонтер'), ('corporate_coordinator', 'Координатор предприятия'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='volunteer', max_length=30, verbose_name='Роль в системе')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('skills', models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Навыки')),
                ('interests', models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Интересы')),
                ('total_volunteer_hours', models.PositiveIntegerField(default=0, verbose_name='Всего часов волонтерства')),
                ('events_participated', models.PositiveIntegerField(default=0, verbose_name='Участий в мероприятиях')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('newsletter_subscription', models.BooleanField(default=True, verbose_name='Подписка на рассылку')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Телефон подтвержден')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email подтвержден')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('profile_update', 'Обновление профиля'), ('password_change', 'Смена пароля'), ('email_verification', 'Подтверждение email')], max_length=50, verbose_name='Действие')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.URLField(blank=True, verbose_name='VK')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Род занятий')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Организация')),
                ('volunteer_experience', models.TextField(blank=True, verbose_name='Опыт волонтерства')),
                ('available_weekdays', models.CharField(blank=True, max_length=100, verbose_name='Доступные дни')),
                ('has_car', models.BooleanField(default=False, verbose_name='Есть автомобиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('email_verification', 'Подтверждение email'), ('phone_verification', 'Подтверждение телефона'), ('password_reset', 'Сброс пароля')], max_length=20, verbose_name='Тип кода')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код верификации',
                'verbose_name_plural': 'Коды верификации',
                'indexes': [models.Index(fields=['user', 'code_type', 'is_used'], name='accounts_ve_user_id_ddbbc5_idx')],
            },
        ),
    ]
